// DO NOT EDIT
// Generated by JFlex 1.9.0 http://jflex.de/
// source: scanner.jflex

//------------------paquetes importaciones
package src;
import java_cup.runtime.*;

//--------opciones y declaraciones

@SuppressWarnings("fallthrough")
public class Analizador implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\2\23\0\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\11\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\2\45\1\53\1\54"+
    "\1\55\1\56\1\45\1\57\1\45\1\60\1\45\1\61"+
    "\1\62\1\63\1\64\1\65\1\0\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\2\45\1\53\1\54\1\55"+
    "\1\56\1\45\1\57\1\45\1\60\1\45\1\66\1\67"+
    "\1\70\1\71\6\0\1\3\252\0\2\72\115\0\1\73"+
    "\u01a8\0\2\3\u0100\0\1\74\325\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\2\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\16\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\2\0\1\43\1\0\1\44\1\45"+
    "\1\46\1\47\1\0\1\50\1\51\1\52\5\53\1\54"+
    "\4\53\1\55\7\53\1\56\1\55\2\0\1\57\1\60"+
    "\6\53\2\0\2\53\1\61\1\62\1\53\1\0\1\63"+
    "\4\53\1\0\1\62\1\0\1\53\1\64\1\53\1\65"+
    "\1\66\1\67\1\66\1\67\1\53\1\0\1\53\2\70"+
    "\2\53\1\0\1\71\1\53\1\0\1\72\2\73\2\74"+
    "\1\75\2\53\1\0\2\76\1\77\2\100";

  private static int [] zzUnpackAction() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\75\0\75\0\75\0\75\0\75"+
    "\0\267\0\75\0\75\0\364\0\u0131\0\75\0\u016e\0\75"+
    "\0\u01ab\0\u01e8\0\u0225\0\75\0\75\0\u0262\0\u029f\0\u02dc"+
    "\0\75\0\75\0\u0319\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a"+
    "\0\u0487\0\u04c4\0\u0501\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632"+
    "\0\75\0\75\0\75\0\75\0\u066f\0\75\0\75\0\75"+
    "\0\75\0\u06ac\0\u06e9\0\75\0\u0726\0\75\0\75\0\75"+
    "\0\75\0\u0763\0\75\0\75\0\75\0\u0487\0\u07a0\0\u07dd"+
    "\0\u081a\0\u0857\0\u0487\0\u0894\0\u08d1\0\u090e\0\u094b\0\u0487"+
    "\0\u0988\0\u09c5\0\u0a02\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6\0\75"+
    "\0\75\0\u0b33\0\u0b70\0\75\0\u0763\0\u0bad\0\u0bea\0\u0c27"+
    "\0\u0c64\0\u0ca1\0\u0cde\0\u0d1b\0\u0d58\0\u0d95\0\u0dd2\0\u0487"+
    "\0\u0487\0\u0e0f\0\u0e4c\0\u0487\0\u0e89\0\u0ec6\0\u0f03\0\u0f40"+
    "\0\u0f7d\0\75\0\u0fba\0\u0ff7\0\u0487\0\u1034\0\u0487\0\u0487"+
    "\0\u0487\0\75\0\75\0\u1071\0\u10ae\0\u10eb\0\u0487\0\75"+
    "\0\u1128\0\u1165\0\u11a2\0\u0487\0\u11df\0\u121c\0\u0487\0\u0487"+
    "\0\75\0\u0487\0\75\0\u0487\0\u1259\0\u1296\0\u12d3\0\u0487"+
    "\0\75\0\u0487\0\u0487\0\75";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\2\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\2\41\1\42\3\41\1\43\1\44\1\41\1\45"+
    "\1\46\1\47\1\41\1\50\1\41\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\126\0\1\64\51\0\1\65\104\0\1\66\75\0\1\67"+
    "\76\0\1\70\3\0\1\23\135\0\1\71\7\0\2\72"+
    "\2\0\73\72\2\0\17\72\2\23\50\72\30\0\1\73"+
    "\74\0\1\74\74\0\1\75\67\0\2\76\7\0\17\76"+
    "\1\77\5\76\4\0\1\76\32\0\2\76\7\0\16\76"+
    "\1\100\1\101\5\76\4\0\1\76\32\0\2\76\7\0"+
    "\7\76\1\102\15\76\4\0\1\76\32\0\2\76\7\0"+
    "\16\76\1\103\6\76\4\0\1\76\32\0\2\76\7\0"+
    "\13\76\1\104\11\76\4\0\1\76\32\0\2\76\7\0"+
    "\1\105\12\76\1\106\2\76\1\107\6\76\4\0\1\76"+
    "\32\0\2\76\7\0\25\76\4\0\1\76\32\0\2\76"+
    "\7\0\5\76\1\110\7\76\1\111\7\76\4\0\1\76"+
    "\32\0\2\76\7\0\1\112\24\76\4\0\1\76\32\0"+
    "\2\76\7\0\16\76\1\113\6\76\4\0\1\76\32\0"+
    "\2\76\7\0\4\76\1\114\20\76\4\0\1\76\32\0"+
    "\2\76\7\0\21\76\1\115\3\76\4\0\1\76\32\0"+
    "\2\76\7\0\17\76\1\116\5\76\4\0\1\76\32\0"+
    "\2\76\7\0\7\76\1\117\15\76\4\0\1\76\31\0"+
    "\1\120\2\76\7\0\25\76\4\0\1\76\50\0\1\121"+
    "\7\0\1\122\100\0\1\123\31\0\1\124\105\0\2\125"+
    "\73\0\2\76\7\0\17\76\1\126\5\76\4\0\1\76"+
    "\32\0\2\76\7\0\16\76\1\127\6\76\4\0\1\76"+
    "\32\0\2\76\7\0\4\76\1\130\20\76\4\0\1\76"+
    "\32\0\2\76\7\0\1\131\24\76\4\0\1\76\32\0"+
    "\2\76\7\0\10\76\1\132\7\76\1\133\4\76\4\0"+
    "\1\76\4\0\1\134\1\135\24\0\2\76\7\0\13\76"+
    "\1\136\11\76\4\0\1\76\32\0\2\76\7\0\16\76"+
    "\1\137\6\76\4\0\1\76\32\0\2\76\7\0\17\76"+
    "\1\140\5\76\4\0\1\76\32\0\2\76\7\0\21\76"+
    "\1\141\3\76\4\0\1\76\32\0\2\76\7\0\10\76"+
    "\1\142\14\76\4\0\1\76\4\0\1\143\25\0\2\76"+
    "\7\0\21\76\1\144\3\76\4\0\1\76\32\0\2\76"+
    "\7\0\21\76\1\145\3\76\4\0\1\76\32\0\2\76"+
    "\7\0\17\76\1\146\5\76\4\0\1\76\32\0\2\76"+
    "\7\0\22\76\1\147\2\76\4\0\1\76\32\0\2\76"+
    "\7\0\10\76\1\150\14\76\4\0\1\76\4\0\1\151"+
    "\57\0\1\152\72\0\1\153\44\0\2\76\7\0\1\154"+
    "\24\76\4\0\1\76\32\0\2\76\7\0\13\76\1\155"+
    "\11\76\4\0\1\76\32\0\2\76\7\0\1\156\24\76"+
    "\4\0\1\76\32\0\2\76\7\0\17\76\1\157\5\76"+
    "\4\0\1\76\32\0\2\76\7\0\5\76\1\160\17\76"+
    "\4\0\1\76\32\0\2\76\7\0\4\76\1\161\20\76"+
    "\4\0\1\76\50\0\1\162\73\0\1\163\57\0\2\76"+
    "\7\0\20\76\1\164\4\76\4\0\1\76\5\0\1\165"+
    "\24\0\2\76\7\0\1\166\24\76\4\0\1\76\32\0"+
    "\2\76\7\0\15\76\1\167\7\76\4\0\1\76\60\0"+
    "\1\170\46\0\2\76\7\0\22\76\1\171\2\76\4\0"+
    "\1\76\32\0\2\76\7\0\10\76\1\172\14\76\4\0"+
    "\1\76\4\0\1\173\25\0\2\76\7\0\4\76\1\174"+
    "\20\76\4\0\1\76\32\0\2\76\7\0\13\76\1\175"+
    "\11\76\4\0\1\76\56\0\1\176\71\0\1\173\25\0"+
    "\1\173\25\0\2\76\7\0\24\76\1\177\4\0\1\76"+
    "\32\0\2\76\7\0\12\76\1\200\12\76\4\0\1\76"+
    "\6\0\1\201\23\0\2\76\7\0\4\76\1\202\20\76"+
    "\4\0\1\76\47\0\1\203\57\0\2\76\7\0\21\76"+
    "\1\204\3\76\4\0\1\76\32\0\2\76\7\0\17\76"+
    "\1\205\5\76\4\0\1\76\32\0\2\76\7\0\15\76"+
    "\1\206\7\76\4\0\1\76\60\0\1\207\46\0\2\76"+
    "\7\0\4\76\1\210\20\76\4\0\1\76\47\0\1\211"+
    "\57\0\2\76\7\0\15\76\1\212\7\76\4\0\1\76"+
    "\32\0\2\76\7\0\6\76\1\213\16\76\4\0\1\76"+
    "\51\0\1\214\32\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4880];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\5\11\1\1\2\11\2\1\1\11"+
    "\1\1\1\11\3\1\2\11\3\1\2\11\16\1\4\11"+
    "\1\1\4\11\2\0\1\11\1\0\4\11\1\0\3\11"+
    "\22\1\2\11\2\0\1\11\7\1\2\0\5\1\1\0"+
    "\5\1\1\0\1\11\1\0\6\1\2\11\1\1\1\0"+
    "\2\1\1\11\2\1\1\0\2\1\1\0\2\1\1\11"+
    "\1\1\1\11\3\1\1\0\1\1\1\11\2\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analizador(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /*ignore*/
            }
          // fall through
          case 65: break;
          case 2:
            { return new Symbol(sym.REXC, yycolumn, yyline, yytext());
            }
          // fall through
          case 66: break;
          case 3:
            { return new Symbol(sym.COMILLADOB, yycolumn, yyline, yytext());
            }
          // fall through
          case 67: break;
          case 4:
            { return new Symbol(sym.HASH, yycolumn, yyline, yytext());
            }
          // fall through
          case 68: break;
          case 5:
            { return new Symbol(sym.DOLLAR, yycolumn, yyline, yytext());
            }
          // fall through
          case 69: break;
          case 6:
            { return new Symbol(sym.PORCIENTO, yycolumn, yyline, yytext());
            }
          // fall through
          case 70: break;
          case 7:
            { return new Symbol(sym.AND, yycolumn, yyline, yytext());
            }
          // fall through
          case 71: break;
          case 8:
            { return new Symbol(sym.COMILLASIM, yycolumn, yyline, yytext());
            }
          // fall through
          case 72: break;
          case 9:
            { return new Symbol(sym.LPAREN, yycolumn, yyline, yytext());
            }
          // fall through
          case 73: break;
          case 10:
            { return new Symbol(sym.RPAREN, yycolumn, yyline, yytext());
            }
          // fall through
          case 74: break;
          case 11:
            { return new Symbol(sym.MULT, yycolumn, yyline, yytext());
            }
          // fall through
          case 75: break;
          case 12:
            { return new Symbol(sym.MAS, yycolumn, yyline, yytext());
            }
          // fall through
          case 76: break;
          case 13:
            { return new Symbol(sym.COMA, yycolumn, yyline, yytext());
            }
          // fall through
          case 77: break;
          case 14:
            { return new Symbol(sym.MENOS, yycolumn, yyline, yytext());
            }
          // fall through
          case 78: break;
          case 15:
            { return new Symbol(sym.PUNTO, yycolumn, yyline, yytext());
            }
          // fall through
          case 79: break;
          case 16:
            { return new Symbol(sym.DIV, yycolumn, yyline, yytext());
            }
          // fall through
          case 80: break;
          case 17:
            { return new Symbol(sym.numero, yycolumn, yyline, yytext());
            }
          // fall through
          case 81: break;
          case 18:
            { return new Symbol(sym.DOSPUNTOS, yycolumn, yyline, yytext());
            }
          // fall through
          case 82: break;
          case 19:
            { return new Symbol(sym.SEMICOLON, yycolumn, yyline, yytext());
            }
          // fall through
          case 83: break;
          case 20:
            { return new Symbol(sym.MENOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 84: break;
          case 21:
            { return new Symbol(sym.ASIGNACION, yycolumn, yyline, yytext());
            }
          // fall through
          case 85: break;
          case 22:
            { return new Symbol(sym.MAYOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 86: break;
          case 23:
            { return new Symbol(sym.RINTERRO, yycolumn, yyline, yytext());
            }
          // fall through
          case 87: break;
          case 24:
            { return new Symbol(sym.ARROBA, yycolumn, yyline, yytext());
            }
          // fall through
          case 88: break;
          case 25:
            { return new Symbol(sym.letra, yycolumn, yyline, yytext());
            }
          // fall through
          case 89: break;
          case 26:
            { return new Symbol(sym.LBRACKET, yycolumn, yyline, yytext());
            }
          // fall through
          case 90: break;
          case 27:
            { return new Symbol(sym.SLASH, yycolumn, yyline, yytext());
            }
          // fall through
          case 91: break;
          case 28:
            { return new Symbol(sym.RBRACKET, yycolumn, yyline, yytext());
            }
          // fall through
          case 92: break;
          case 29:
            { return new Symbol(sym.CONJ, yycolumn, yyline, yytext());
            }
          // fall through
          case 93: break;
          case 30:
            { return new Symbol(sym.GUIONBAJO, yycolumn, yyline, yytext());
            }
          // fall through
          case 94: break;
          case 31:
            { return new Symbol(sym.LBRACE, yycolumn, yyline, yytext());
            }
          // fall through
          case 95: break;
          case 32:
            { return new Symbol(sym.PIPE, yycolumn, yyline, yytext());
            }
          // fall through
          case 96: break;
          case 33:
            { return new Symbol(sym.RBRACE, yycolumn, yyline, yytext());
            }
          // fall through
          case 97: break;
          case 34:
            { return new Symbol(sym.MODULO, yycolumn, yyline, yytext());
            }
          // fall through
          case 98: break;
          case 35:
            { return new Symbol(sym.NOTEQUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 99: break;
          case 36:
            { return new Symbol(sym.POTENCIA, yycolumn, yyline, yytext());
            }
          // fall through
          case 100: break;
          case 37:
            { return new Symbol(sym.INCREMENTO, yycolumn, yyline, yytext());
            }
          // fall through
          case 101: break;
          case 38:
            { return new Symbol(sym.DECREMENTO, yycolumn, yyline, yytext());
            }
          // fall through
          case 102: break;
          case 39:
            { return new Symbol(sym.LCOMENTB, yycolumn, yyline, yytext());
            }
          // fall through
          case 103: break;
          case 40:
            { return new Symbol(sym.MENORIGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 104: break;
          case 41:
            { return new Symbol(sym.EQUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 105: break;
          case 42:
            { return new Symbol(sym.MAYORIGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 106: break;
          case 43:
            { return new Symbol(sym.IDENTIFICADOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 107: break;
          case 44:
            { return new Symbol(sym.DO, yycolumn, yyline, yytext());
            }
          // fall through
          case 108: break;
          case 45:
            { return new Symbol(sym.IF, yycolumn, yyline, yytext());
            }
          // fall through
          case 109: break;
          case 46:
            { return new Symbol(sym.RCOMENTB, yycolumn, yyline, yytext());
            }
          // fall through
          case 110: break;
          case 47:
            { return new Symbol(sym.simbolo, yycolumn, yyline, yytext());
            }
          // fall through
          case 111: break;
          case 48:
            { return new Symbol(sym.floatN, yycolumn, yyline, yytext());
            }
          // fall through
          case 112: break;
          case 49:
            { return new Symbol(sym.FOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 113: break;
          case 50:
            { return new Symbol(sym.INT, yycolumn, yyline, yytext());
            }
          // fall through
          case 114: break;
          case 51:
            { return new Symbol(sym.NOT, yycolumn, yyline, yytext());
            }
          // fall through
          case 115: break;
          case 52:
            { return new Symbol(sym.BOOL, yycolumn, yyline, yytext());
            }
          // fall through
          case 116: break;
          case 53:
            { return new Symbol(sym.CHAR, yycolumn, yyline, yytext());
            }
          // fall through
          case 117: break;
          case 54:
            { return new Symbol(sym.ELIF, yycolumn, yyline, yytext());
            }
          // fall through
          case 118: break;
          case 55:
            { return new Symbol(sym.ELSE, yycolumn, yyline, yytext());
            }
          // fall through
          case 119: break;
          case 56:
            { return new Symbol(sym.MAIN, yycolumn, yyline, yytext());
            }
          // fall through
          case 120: break;
          case 57:
            { return new Symbol(sym.TRUE, yycolumn, yyline, yytext());
            }
          // fall through
          case 121: break;
          case 58:
            { return new Symbol(sym.ARRAY, yycolumn, yyline, yytext());
            }
          // fall through
          case 122: break;
          case 59:
            { return new Symbol(sym.BREAK, yycolumn, yyline, yytext());
            }
          // fall through
          case 123: break;
          case 60:
            { return new Symbol(sym.FALSE, yycolumn, yyline, yytext());
            }
          // fall through
          case 124: break;
          case 61:
            { return new Symbol(sym.FLOAT, yycolumn, yyline, yytext());
            }
          // fall through
          case 125: break;
          case 62:
            { return new Symbol(sym.WHILE, yycolumn, yyline, yytext());
            }
          // fall through
          case 126: break;
          case 63:
            { return new Symbol(sym.RETURN, yycolumn, yyline, yytext());
            }
          // fall through
          case 127: break;
          case 64:
            { return new Symbol(sym.STRING, yycolumn, yyline, yytext());
            }
          // fall through
          case 128: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
