
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package src;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACKET = 13;
  public static final int MULT = 7;
  public static final int CHAR = 33;
  public static final int NOTEQUAL = 24;
  public static final int LPAREN = 8;
  public static final int INT = 30;
  public static final int ARRAY = 34;
  public static final int FOR = 42;
  public static final int REXC = 2;
  public static final int RPAREN = 9;
  public static final int NOT = 29;
  public static final int MENORIGUAL = 21;
  public static final int AND = 6;
  public static final int OR = 4;
  public static final int BOOL = 35;
  public static final int ARROBA = 3;
  public static final int ESCRIBIR = 46;
  public static final int DIV = 20;
  public static final int INCREMENTO = 27;
  public static final int IF = 37;
  public static final int MAIN = 36;
  public static final int RCOMENTB = 48;
  public static final int MAYORIGUAL = 22;
  public static final int EOF = 0;
  public static final int RETURN = 43;
  public static final int ASIG = 12;
  public static final int RBRACKET = 14;
  public static final int EQUAL = 23;
  public static final int DECREMENTO = 28;
  public static final int error = 1;
  public static final int COMA = 17;
  public static final int LITERAL_CHAR = 52;
  public static final int MODULO = 26;
  public static final int MENOS = 10;
  public static final int MENOR = 18;
  public static final int BREAK = 44;
  public static final int LITERAL_FLOAT = 50;
  public static final int MAYOR = 19;
  public static final int POTENCIA = 25;
  public static final int LITERAL_INT = 49;
  public static final int ELSE = 39;
  public static final int LBRACE = 15;
  public static final int LITERAL_STRING = 53;
  public static final int WHILE = 40;
  public static final int DOLLAR = 5;
  public static final int FLOAT = 31;
  public static final int RBRACE = 16;
  public static final int LEER = 45;
  public static final int LITERAL_BOOL = 51;
  public static final int STRING = 32;
  public static final int ELIF = 38;
  public static final int DO = 41;
  public static final int IDENTIFIER = 54;
  public static final int LCOMENTB = 47;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "REXC",
  "ARROBA",
  "OR",
  "DOLLAR",
  "AND",
  "MULT",
  "LPAREN",
  "RPAREN",
  "MENOS",
  "MAS",
  "ASIG",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "COMA",
  "MENOR",
  "MAYOR",
  "DIV",
  "MENORIGUAL",
  "MAYORIGUAL",
  "EQUAL",
  "NOTEQUAL",
  "POTENCIA",
  "MODULO",
  "INCREMENTO",
  "DECREMENTO",
  "NOT",
  "INT",
  "FLOAT",
  "STRING",
  "CHAR",
  "ARRAY",
  "BOOL",
  "MAIN",
  "IF",
  "ELIF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "RETURN",
  "BREAK",
  "LEER",
  "ESCRIBIR",
  "LCOMENTB",
  "RCOMENTB",
  "LITERAL_INT",
  "LITERAL_FLOAT",
  "LITERAL_BOOL",
  "LITERAL_CHAR",
  "LITERAL_STRING",
  "IDENTIFIER"
  };
}

